version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
  frontend:
    build:
      context: ./ecommerce
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./ecommerce:/app
    stdin_open: true
    depends_on:
      - backend

  backend:
    build:
      context: ./ecommerce-api
      dockerfile: Dockerfile
    volumes:
      - ./ecommerce-api:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    depends_on:
      - db