# Generated by Django 5.1 on 2024-08-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_option_part_alter_part_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='option',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='options',
            field=models.ManyToManyField(to='api.option'),
        ),
    ]
