# Generated by Django 5.1 on 2024-08-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_orderitem_option_orderitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
