superuser:
	docker-compose exec backend python manage.py createsuperuser

test:
	docker-compose exec backend python manage.py test

loaddata:
	docker-compose exec backend python manage.py loaddata fixtures/api.json
